//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Sport_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime OrderData { get; set; }
        public System.DateTime OrderDelivery { get; set; }
        public int PickupPoint { get; set; }
        public string OrderSostav { get; set; }
        public int CodeDelivery { get; set; }
        public string Status { get; set; }
        public string FIOKlient { get; set; }
    
        public virtual PickupPoint PickupPoint1 { get; set; }
        public virtual User User { get; set; }
    }
}
