//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Sport_Product.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductArticle { get; set; }
        public string ProductName { get; set; }
        public int ProductUnitID { get; set; }
        public int ProductCost { get; set; }
        public int ProductMaxSale { get; set; }
        public int ProductManufacturerID { get; set; }
        public int ProductSale { get; set; }
        public int ProductCount { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
        public int ProductCategoryID { get; set; }
        public int ProductProviderID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
